

#include "pointsmodel.h"

#include <qfontdatabase.h>
#include <qdebug.h>
#include <qimage.h>
#include <qicon.h>

#include <klocalizedstring.h>
#include <kcolorscheme.h>

#include "trackdata.h"
#include "filesmodel.h"


enum COLUMN
{
    COL_NAME,						// name
    COL_SYM,						// symbol
    COL_ORIGIN,						// data source ID
    COL_COORDS,						// lat/long coordinates
    COL_ADDRESS,					// street address
    COL_CATS,						// catgeories
    COL_COUNT						// how many - must be last
};


#define SIZE_ICON		QSize(16, 16)
#define SIZE_HINT		QSize(18, 18)


PointsModel::PointsModel(QObject *pnt)
    : QAbstractItemModel(pnt)
{
    qDebug();
}


QModelIndex PointsModel::index(int row, int col, const QModelIndex &pnt) const
{
    return (createIndex(row, col, row));
}


QModelIndex PointsModel::parent(const QModelIndex &idx) const
{
    return (QModelIndex());
}


int PointsModel::rowCount(const QModelIndex &pnt) const
{
    return (mPoints.count());
}


int PointsModel::columnCount(const QModelIndex &pnt) const
{
    return (COL_COUNT);
}


static QVariant formatCoordinates(const TrackDataItem *item)
{
    const TrackDataAbstractPoint *tdp = dynamic_cast<const TrackDataAbstractPoint *>(item);
    if (tdp==nullptr) return (QVariant());
    return (tdp->formattedPosition());
}


// Based on NavMarks PointData::displayAddress()
static QVariant formatAddress(const TrackDataItem *item)
{
    QStringList result;

    // "StreetAddress", which may be multiple lines
    const QString street = item->metadata("StreetAddress").toString();
    if (!street.isEmpty()) result.append(street.split("\n", Qt::SkipEmptyParts));

    // "City"
    const QString city = item->metadata("City").toString();
    if (!city.isEmpty()) result.append(city);

    // "State", if not the same as "City"
    // and not the same as the first two of "PostalCode" (France departement)
    const QString state = item->metadata("State").toString();
    const QString pcode = item->metadata("PostalCode").toString();
    if (!state.isEmpty() && state!=city &&
        !(state.length()==2 && state==pcode.left(2))) result.append(state);

    const QString cntry =  item->metadata("Country").toString();
    if (!pcode.isEmpty() && !cntry.isEmpty())
    {
        // "PostalCode - Country" if both are present
        result.append(pcode+" - "+cntry);
    }
    else
    {
        // "PostalCode" or "Country"
        if (!pcode.isEmpty()) result.append(pcode);
        if (!cntry.isEmpty()) result.append(cntry);
    }

    return (result.join(", "));
}


QVariant PointsModel::data(const QModelIndex &idx, int role) const
{
    const TrackDataItem *item = mPoints.value(idx.row());
    if (item==nullptr) return (QVariant());

    switch (role)
    {
case Qt::DisplayRole:
        switch (idx.column())
        {
case COL_NAME:     return (item->name());
case COL_ORIGIN:   return (item->metadata("origin").toString().split(',').join(", "));
case COL_COORDS:   return (formatCoordinates(item));
case COL_ADDRESS:  return (formatAddress(item));
case COL_CATS:     return (item->metadata("category").toString().split(',').join(", "));
        }
        break;

case Qt::DecorationRole:
        switch (idx.column())
        {
case COL_SYM:      // TODO: Garmin icons via IconsManager
                   //const QImage *img = controller()->iconsManager()->iconForName(p->symbol());
                   //if (img!=NULL) return (img->scaled(SIZE_ICON));
                   return (item->icon());
        }
        break;

case Qt::FontRole:
        switch (idx.column())
        {
case COL_COORDS:   return (QFontDatabase::systemFont(QFontDatabase::FixedFont));
        }
        break;

case Qt::ForegroundRole:
        if (idx.column()==COL_NAME)
        {
            const KColorScheme sch;
            const TrackData::WaypointFlags flags = static_cast<TrackData::WaypointFlags>(item->metadata("flags").toInt());

            if (flags & TrackData::NewlyImported) return (sch.foreground(KColorScheme::PositiveText));
            if (flags & TrackData::NoExport) return (sch.foreground(KColorScheme::NegativeText));
        }
        break;

case Qt::ToolTipRole:
        switch (idx.column())
        {
            // TODO: this will be blank for icons generated by WaypointImageProvider, with
            // no means to set the name.  Possibly also for icons to be loaded by the Garmin
            // symbols manager too.  Maybe need a separate NamedIcon type subclassing a
            // QIcon with the option to set the name appropriately.
case COL_SYM:      return (item->icon().name());
case COL_ORIGIN:   return (item->metadata("origin").toString().split(',').join("<br/>"));
        }
        break;

case Qt::UserRole:					// data for sorting
        switch (idx.column())
        {
case COL_SYM:      return (item->icon().name());
default:           return (data(idx, Qt::DisplayRole));
        }
        break;

case Qt::SizeHintRole:
        switch (idx.column())
        {
case COL_SYM:      return (SIZE_HINT);
        }
        break;
    }

    return (QVariant());
}


QVariant PointsModel::headerData(int section, Qt::Orientation orientation, int role) const
{
    if (role!=Qt::DisplayRole) return (QVariant());
    if (orientation!=Qt::Horizontal) return (QVariant());

    switch (section)
    {
case COL_NAME:		return (i18n("Name"));
case COL_SYM:		return (i18n("Sym"));
case COL_ORIGIN:	return (i18n("Origin"));
case COL_COORDS:	return (i18n("Lat/Long"));
case COL_ADDRESS:	return (i18n("Address"));
case COL_CATS:		return (i18n("Categories"));

default:		return (QVariant());
    }
}


Qt::ItemFlags PointsModel::flags(const QModelIndex &idx) const
{
    return (Qt::ItemIsSelectable|Qt::ItemIsEnabled|Qt::ItemNeverHasChildren);
}


void PointsModel::setSourceModel(QAbstractItemModel *srcModel)
{
    qDebug();

    mSourceModel = srcModel;
    connect(srcModel, &QAbstractItemModel::modelReset, this, &PointsModel::slotRebuildPointsList);
    connect(srcModel, &QAbstractItemModel::layoutChanged, this, &PointsModel::slotRebuildPointsList);

    slotRebuildPointsList();
}


void PointsModel::slotRebuildPointsList()
{
    beginResetModel();
    mPoints.clear();

    FilesModel *filesModel = qobject_cast<FilesModel *>(mSourceModel);
    Q_ASSERT(filesModel!=nullptr);
    const TrackDataItem *root = filesModel->rootFileItem();
    if (root!=nullptr) buildPointsList(root);		// may not have been set yet

    endResetModel();
    qDebug() << "total points" << mPoints.count();
}


void PointsModel::buildPointsList(const TrackDataItem *item)
{
    if (dynamic_cast<const TrackDataWaypoint *>(item)!=nullptr) mPoints.append(item);
    else
    {
        const int n = item->childCount();
        for (int i = 0; i<n; ++i) buildPointsList(item->childAt(i));
    }
}


const TrackDataItem *PointsModel::itemAt(int row)
{
    return (mPoints.value(row));
}
